<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2011-09-01 11:20

$extensionPath = t3lib_extMgm::extPath('gridelements');
return array(
	'tx_gridelements_addjavascript' => $extensionPath . 'lib/class.tx_gridelements_addjavascript.php',
	'tx_gridelements_cmoptions' => $extensionPath . 'lib/class.tx_gridelements_cmoptions.php',
	'tx_gridelements_colposlist' => $extensionPath . 'lib/class.tx_gridelements_colposlist.php',
	'tx_gridelements_dblisthook' => $extensionPath . 'lib/class.tx_gridelements_dblisthook.php',
	'tx_gridelements_drawitemhook' => $extensionPath . 'lib/class.tx_gridelements_drawitemhook.php',
	'tx_gridelements_layoutsetup' => $extensionPath . 'lib/class.tx_gridelements_layoutsetup.php',
	'tx_gridelements_tceformshook' => $extensionPath . 'lib/class.tx_gridelements_tceformshook.php',
	'tx_gridelements_tcemainhook' => $extensionPath . 'lib/class.tx_gridelements_tcemainhook.php',
	'tx_gridelements_tt_content' => $extensionPath . 'lib/class.tx_gridelements_tt_content.php',
	'tx_gridelements_wizarditemshook' => $extensionPath . 'lib/class.tx_gridelements_wizarditemshook.php',
	'tx_gridelements_pi1' => $extensionPath . 'pi1/class.tx_gridelements_pi1.php',
);
?>